### ISSUE TITLE
PBWoW3xgame

### ISSUE THREAD

**Issue by Galixte** [Sajaki/pbwowext#8]
Hi @Sajaki,

do you have an idea about the future of this extension: https://github.com/PayBas/PBWoW3xgame?

Maybe you have incorporated this in https://github.com/Sajaki/PBWoW3ext, i don’t know.

**Comment by Inkoming** [comment]
The link you're talking about is a 404 error page.
What is it the PBWoW3xgame?

**Comment by Galixte** [comment]
Hi @Inkoming,

the first link is fixed. ;)

It was a complement for the PBWoW3ext extension.
